### ISSUE TITLE
Error running plugin cif, caused by KeyError('address',)

### ISSUE THREAD

**Issue by a5m0** [JustinAzoff/ninfo-plugin-cif#1]
$ sudo ninfo -p cif google.com
/usr/local/lib/python2.7/dist-packages/requests-2.8.1-py2.7.egg/requests/packages/urllib3/util/ssl_.py:100: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/usr/local/lib/python2.7/dist-packages/requests-2.8.1-py2.7.egg/requests/packages/urllib3/connectionpool.py:789: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
ERROR:ninfo:Error running plugin cif
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ninfo-0.5.2-py2.7.egg/ninfo/**init**.py", line 278, in get_info
    ret = plugin_obj.get_info(arg)
  File "/usr/local/lib/python2.7/dist-packages/ninfo_plugin_cif-0.3-py2.7.egg/ninfo_plugin_cif/**init**.py", line 25, in get_info
    tup = (r["address"], r["description"], r["alternativeid"], r.get("portlist"))
KeyError: 'address'
/usr/local/lib/python2.7/dist-packages/requests-2.8.1-py2.7.egg/requests/packages/urllib3/connectionpool.py:789: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
ERROR:ninfo:Error running plugin cif
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ninfo-0.5.2-py2.7.egg/ninfo/**init**.py", line 278, in get_info
    ret = plugin_obj.get_info(arg)
  File "/usr/local/lib/python2.7/dist-packages/ninfo_plugin_cif-0.3-py2.7.egg/ninfo_plugin_cif/**init**.py", line 25, in get_info
    tup = (r["address"], r["description"], r["alternativeid"], r.get("portlist"))
KeyError: 'address'
ERROR:ninfo:Error running plugin cif
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ninfo-0.5.2-py2.7.egg/ninfo/**init**.py", line 315, in get_info_iter
    result = self.get_info(p.name, arg, options)
  File "/usr/local/lib/python2.7/dist-packages/ninfo-0.5.2-py2.7.egg/ninfo/**init**.py", line 287, in get_info
    return self.get_info(plugin, arg, options, retries-1)
  File "/usr/local/lib/python2.7/dist-packages/ninfo-0.5.2-py2.7.egg/ninfo/**init**.py", line 288, in get_info
    raise PluginError("Error running plugin %s"% plugin, cause=e)
PluginError: Error running plugin cif, caused by KeyError('address',)

**Comment by JustinAzoff** [comment]
Do you know what version of the server you are running? That query works here..

Can you temporarily change the ninfo_plugin_cif/**init**.py file to look like

```
def get_info(self, arg):
    results = self.cif.search(q=arg)
    print results # add this
```

And see what that outputs.  I must not be handling an error condition.. I bet results is something like ["invalid api key"].

**Comment by a5m0** [comment]
I am running a cifv2 server, so I've been working on updating https://github.com/JustinAzoff/cif-http-client-python/blob/master/cif_http_client.py

**Comment by a5m0** [comment]
these are the changes I made to get it working with cifv2 https://gist.github.com/a5m0/a2daf7617136149adcac978010dfb360 , currently working on ninfo-plugin-cif to get it to work as well

**Comment by JustinAzoff** [comment]
@wesyoung Should I port stuff to use your python SDK now?  I think my cif-http-client-python is obsolete now?

**Comment by wesyoung** [comment]
i think so....

https://github.com/csirtgadgets/cif-sdk-py/blob/master/cifsdk/client.py#L296
https://github.com/csirtgadgets/cif-sdk-py/blob/master/cifsdk/client.py#L63
